// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zeus.Academia.Features.Extensions.ProvisionExtension;

#nullable disable

namespace Zeus.Academia.Features.Extensions.ProvisionExtension.Shared.Migrations
{
    [DbContext(typeof(ProvisionExtensionDbContext))]
    partial class ProvisionExtensionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zeus.Academia.Features.SharedKernel.Foundation.Domain.Extension", b =>
                {
                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("AssignedEmpNr")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Number");

                    b.HasIndex("AssignedEmpNr")
                        .IsUnique()
                        .HasFilter("[AssignedEmpNr] IS NOT NULL");

                    b.ToTable("Extensions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
