// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zeus.Academia.Features.ReferenceData.ManageUniversities;

#nullable disable

namespace Zeus.Academia.Features.ReferenceData.ManageUniversities.Shared.Migrations
{
    [DbContext(typeof(ManageUniversitiesDbContext))]
    partial class ManageUniversitiesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zeus.Academia.Features.ReferenceData.ManageUniversities.UniversityRecord", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Code");

                    b.ToTable("Universities", null, t =>
                        {
                            t.HasCheckConstraint("CK_Universities_Code_Allowed", "[Code] IN ('BOSTON_U', 'MIT', 'STANFORD')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
